version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_REPO: https://github.com/renanzitoo/dashboard.git
    container_name: nextjs-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge
